### ISSUE TITLE
Can you include the snapcraft code in the Github repository?

### ISSUE THREAD

**Issue by argosopentech** [clockback/prosakart#2]
Hi,

I've been struggling to get a tkinter application running in a snap container. Someone on this [forum](https://forum.snapcraft.io/t/tkinter-doesnt-work-with-the-python-plugin/16567/11) pointed out that you have a tkinter application working in a snap. I got your snap from the snap store and it worked on my computer.

Can you include the snapcraft code in the Github repository?

**Comment by clockback** [comment]
I'm glad to hear you're interested. I haven't touched the snap for months, so I can't be _certain_ that it's all up to scratch. I've committed the snapcraft.yaml file to the repository, under the /snap folder. Best of luck!

**Comment by argosopentech** [comment]
Thanks!
